# infrastructure/resilience/ — Circuit breakers, retry policies, and connection management.

from infrastructure.resilience.circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitBreakerError,
    CircuitBreakerOpenError,
    CircuitBreakerState,
    StateChangeEvent,
    clear_registry,
    get_all_breakers,
    get_circuit_breaker,
    register_circuit_breaker,
    with_circuit_breaker,
)
from infrastructure.resilience.degradation_coordinator import (
    DegradationCoordinator,
    DegradationEvent,
    DegradationLevel,
    DegradationPolicy,
    create_degradation_coordinator,
    get_current_degradation_level,
    get_degradation_coordinator,
    is_feature_enabled,
    reset_degradation_coordinator,
    should_use_local_speech,
)
from infrastructure.resilience.error_classifier import (
    ErrorCategory,
    ErrorClassification,
    classify_error,
    classify_status_code,
)
from infrastructure.resilience.health_registry import (
    HealthSummary,
    ServiceHealth,
    ServiceHealthRegistry,
    ServiceStatus,
    async_get_health_summary,
    get_health_registry,
    get_service_health,
    get_system_health_score,
    is_system_degraded,
    reset_health_registry,
)
from infrastructure.resilience.retry_policy import (
    RetryConfig,
    RetryPolicy,
    get_retry_policy,
    with_retry,
)
from infrastructure.resilience.timeout_config import (
    AsyncTimeoutContext,
    TimeoutConfig,
    TimeoutError,
    get_timeout,
    get_timeout_config,
    reset_timeout_config,
    run_sync_with_timeout,
    run_with_timeout,
    with_async_timeout,
    with_timeout,
)

__all__ = [
    # Circuit breaker
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitBreakerError",
    "CircuitBreakerOpenError",
    "CircuitBreakerState",
    "StateChangeEvent",
    "clear_registry",
    "get_all_breakers",
    "get_circuit_breaker",
    "register_circuit_breaker",
    "with_circuit_breaker",
    # Error classifier
    "ErrorCategory",
    "ErrorClassification",
    "classify_error",
    "classify_status_code",
    # Retry policy
    "RetryConfig",
    "RetryPolicy",
    "get_retry_policy",
    "with_retry",
    # Health registry
    "HealthSummary",
    "ServiceHealth",
    "ServiceHealthRegistry",
    "ServiceStatus",
    "async_get_health_summary",
    "get_health_registry",
    "get_service_health",
    "get_system_health_score",
    "is_system_degraded",
    "reset_health_registry",
    # Degradation coordinator
    "DegradationCoordinator",
    "DegradationEvent",
    "DegradationLevel",
    "DegradationPolicy",
    "create_degradation_coordinator",
    "get_current_degradation_level",
    "get_degradation_coordinator",
    "is_feature_enabled",
    "reset_degradation_coordinator",
    "should_use_local_speech",
    # Timeout configuration
    "AsyncTimeoutContext",
    "TimeoutConfig",
    "TimeoutError",
    "get_timeout",
    "get_timeout_config",
    "reset_timeout_config",
    "run_sync_with_timeout",
    "run_with_timeout",
    "with_async_timeout",
    "with_timeout",
]
