# shared/config — Configuration management
from .secret_provider import SecretProvider, create_secret_provider
from .settings import (
    SECRETS,
    action_enabled,
    audio_enabled,
    face_enabled,
    get_config,
    get_continuous_config,
    get_debounce_config,
    get_face_config,
    get_live_frame_config,
    get_qr_config,
    get_secret_provider,
    get_spatial_config,
    get_watchdog_config,
    get_worker_config,
    qr_enabled,
    spatial_enabled,
    validate_config,
)

__all__ = [
    "SECRETS",
    "get_config",
    "spatial_enabled",
    "get_spatial_config",
    "qr_enabled",
    "get_qr_config",
    "get_live_frame_config",
    "get_debounce_config",
    "get_watchdog_config",
    "get_continuous_config",
    "get_worker_config",
    "get_face_config",
    "face_enabled",
    "audio_enabled",
    "action_enabled",
    "get_secret_provider",
    "SecretProvider",
    "create_secret_provider",
    "validate_config",
]
