"""Observability adapters for infrastructure monitoring."""

from infrastructure.monitoring.collector import (
    InMemoryMetrics,
    MetricsCollector,
    NullMetrics,
    create_metrics_collector,
)

from infrastructure.monitoring.prometheus_metrics import (
    PrometheusMetrics,
    CircuitBreakerState,
    ServiceName,
    ModelName,
    get_metrics,
    reset_metrics,
    is_prometheus_available,
    timed_request,
    timed_inference,
)

from infrastructure.monitoring.instrumentation import (
    VisionStage,
    RAGStage,
    SpeechStage,
    PipelineStageMetrics,
    timed_stage,
    async_timed_stage,
    instrument_stage,
    instrument_vision,
    instrument_rag,
    instrument_speech,
    FAISSMetricsTracker,
    CircuitBreakerMetricsTracker,
    WebRTCMetricsTracker,
    record_stt_latency,
    record_tts_latency,
    record_llm_latency,
    timed_stt,
    timed_tts,
    timed_llm,
    async_timed_stt,
    async_timed_tts,
    async_timed_llm,
    update_resource_metrics,
    get_webrtc_tracker,
    get_faiss_tracker,
    get_circuit_breaker_tracker,
    reset_trackers,
)

__all__ = [
    "MetricsCollector",
    "InMemoryMetrics",
    "NullMetrics",
    "create_metrics_collector",
    "PrometheusMetrics",
    "CircuitBreakerState",
    "ServiceName",
    "ModelName",
    "get_metrics",
    "reset_metrics",
    "is_prometheus_available",
    "timed_request",
    "timed_inference",
    # Instrumentation exports
    "VisionStage",
    "RAGStage",
    "SpeechStage",
    "PipelineStageMetrics",
    "timed_stage",
    "async_timed_stage",
    "instrument_stage",
    "instrument_vision",
    "instrument_rag",
    "instrument_speech",
    "FAISSMetricsTracker",
    "CircuitBreakerMetricsTracker",
    "WebRTCMetricsTracker",
    "record_stt_latency",
    "record_tts_latency",
    "record_llm_latency",
    "timed_stt",
    "timed_tts",
    "timed_llm",
    "async_timed_stt",
    "async_timed_tts",
    "async_timed_llm",
    "update_resource_metrics",
    "get_webrtc_tracker",
    "get_faiss_tracker",
    "get_circuit_breaker_tracker",
    "reset_trackers",
]
