"""
Script to generate a comprehensive Word document with
Workflow, Dataflow, Architecture Diagram, and HLD
for Voice & Vision Assistant for Blind
"""

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.table import WD_TABLE_ALIGNMENT

def add_heading_style(doc):
    """Add custom styles to the document"""
    styles = doc.styles
    
    # Title style
    style = styles['Title']
    style.font.size = Pt(28)
    style.font.bold = True
    style.font.color.rgb = RGBColor(0, 51, 102)
    
    # Heading 1
    style = styles['Heading 1']
    style.font.size = Pt(18)
    style.font.bold = True
    style.font.color.rgb = RGBColor(0, 51, 102)
    
    # Heading 2
    style = styles['Heading 2']
    style.font.size = Pt(14)
    style.font.bold = True
    style.font.color.rgb = RGBColor(0, 102, 153)

def create_document():
    doc = Document()
    add_heading_style(doc)
    
    # ========== TITLE PAGE ==========
    doc.add_paragraph()
    doc.add_paragraph()
    title = doc.add_heading('Voice & Vision Assistant for Blind', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    subtitle = doc.add_paragraph('Comprehensive Technical Documentation')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.size = Pt(16)
    subtitle.runs[0].font.italic = True
    
    doc.add_paragraph()
    sections = doc.add_paragraph('Workflow | Dataflow | Architecture | High-Level Design (HLD)')
    sections.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sections.runs[0].font.size = Pt(14)
    sections.runs[0].font.bold = True
    
    doc.add_paragraph()
    doc.add_paragraph()
    doc.add_paragraph()
    
    info = doc.add_paragraph()
    info.alignment = WD_ALIGN_PARAGRAPH.CENTER
    info.add_run('Document Version: 1.0\n').bold = True
    info.add_run('Last Updated: February 2, 2026\n')
    info.add_run('Generated by: GitHub Copilot')
    
    doc.add_page_break()
    
    # ========== TABLE OF CONTENTS ==========
    doc.add_heading('Table of Contents', 1)
    
    toc_items = [
        ('1. Executive Summary', 3),
        ('2. System Architecture Diagram', 5),
        ('3. High-Level Design (HLD)', 8),
        ('4. Component Architecture', 11),
        ('5. Workflow Diagrams', 14),
        ('6. Dataflow Diagrams', 17),
        ('7. Technology Stack', 20),
        ('8. API Integration Details', 23),
        ('9. Sequence Diagrams', 25),
        ('10. Deployment Architecture', 27),
        ('11. Performance & Timing', 29),
        ('12. Summary', 31),
    ]
    
    for item, page in toc_items:
        p = doc.add_paragraph()
        p.add_run(item)
        p.add_run(f'{"." * (60 - len(item))} {page}')
    
    doc.add_page_break()
    
    # ========== 1. EXECUTIVE SUMMARY ==========
    doc.add_heading('1. Executive Summary', 1)
    
    doc.add_heading('1.1 Project Overview', 2)
    doc.add_paragraph(
        'The Voice & Vision Assistant for Blind is an AI-powered accessibility solution designed '
        'specifically for blind and visually impaired users. It combines cutting-edge speech recognition, '
        'natural language processing, and computer vision to create an intuitive assistant that helps '
        'users understand their surroundings and interact with the world more confidently.'
    )
    
    doc.add_heading('1.2 Key Objectives', 2)
    objectives = [
        'Real-time Voice Interaction: Seamless speech-to-text and text-to-speech processing',
        'Visual Scene Analysis: AI-powered image understanding and description',
        'Multi-Tool Integration: Calendar, email, contacts, places, and internet search',
        'Low Latency: Streaming responses for natural conversational flow',
        'Privacy-Aware: Thoughtful handling of visual content with people'
    ]
    for obj in objectives:
        doc.add_paragraph(obj, style='List Bullet')
    
    doc.add_heading('1.3 Target Users', 2)
    users = ['Blind individuals', 'Visually impaired users', 'People with low vision', 'Accessibility-focused applications']
    for user in users:
        doc.add_paragraph(user, style='List Bullet')
    
    doc.add_page_break()
    
    # ========== 2. SYSTEM ARCHITECTURE DIAGRAM ==========
    doc.add_heading('2. System Architecture Diagram', 1)
    
    doc.add_heading('2.1 High-Level System Architecture', 2)
    
    arch_text = '''
┌─────────────────────────────────────────────────────────────────────────────┐
│                           ALLY VISION ASSISTANT                              │
│                         Voice & Vision Architecture                          │
└─────────────────────────────────────────────────────────────────────────────┘

                                    ┌─────────────┐
                                    │    USER     │
                                    │  (Blind/VI) │
                                    └──────┬──────┘
                                           │
                   ┌───────────────────────┼───────────────────────┐
                   │                       │                       │
                   ▼                       ▼                       ▼
           ┌───────────────┐       ┌───────────────┐       ┌───────────────┐
           │  Voice Input  │       │ Camera Input  │       │ Audio Output  │
           │  (Microphone) │       │   (WebRTC)    │       │  (Speakers)   │
           └───────┬───────┘       └───────┬───────┘       └───────▲───────┘
                   │                       │                       │
┌──────────────────┼───────────────────────┼───────────────────────┼────────┐
│                  │       LIVEKIT CLOUD    │                      │        │
│                  ▼                        ▼                      │        │
│          ┌───────────────┐        ┌───────────────┐              │        │
│          │  Audio Track  │        │  Video Track  │              │        │
│          │  Subscription │        │  Subscription │              │        │
│          └───────┬───────┘        └───────┬───────┘              │        │
└──────────────────┼────────────────────────┼──────────────────────┼────────┘
                   │                        │                      │
                   ▼                        ▼                      │
┌─────────────────────────────────────────────────────────────────────────────┐
│                         LIVEKIT AGENTS FRAMEWORK                             │
│  ┌────────────┐  ┌────────────┐  ┌────────────┐  ┌────────────┐             │
│  │ Silero VAD │──│ Deepgram   │──│ Ollama LLM │──│ ElevenLabs │─────────────┘
│  │ (Voice     │  │    STT     │  │  (qwen3-vl │  │    TTS     │
│  │ Activity)  │  │ (nova-3)   │  │   :235b)   │  │(multilingual)
│  └────────────┘  └────────────┘  └─────┬──────┘  └────────────┘
│                                        │                                     │
│                                        ▼                                     │
│                           ┌─────────────────────────┐                        │
│                           │   AllyVisionAgent       │                        │
│                           │   (Custom Agent Class)  │                        │
│                           └───────────┬─────────────┘                        │
└───────────────────────────────────────┼──────────────────────────────────────┘
                                        │
    ┌──────────┬──────────┬─────────────┼──────────┬──────────┬──────────┐
    ▼          ▼          ▼             ▼          ▼          ▼          ▼
┌────────┐ ┌────────┐ ┌────────┐ ┌────────┐ ┌────────┐ ┌────────┐ ┌────────┐
│analyze │ │search  │ │search  │ │manage  │ │manage  │ │search  │ │timing  │
│_vision │ │_internet│ │_places │ │_calendar│ │_comm  │ │_general│ │profiler│
└───┬────┘ └───┬────┘ └───┬────┘ └───┬────┘ └───┬────┘ └────────┘ └────────┘
    │          │          │          │          │
    ▼          ▼          ▼          ▼          ▼
┌────────┐ ┌────────┐ ┌────────┐ ┌────────┐ ┌────────┐
│ Ollama │ │DuckDuck│ │  OSM   │ │ Local  │ │IMAP/   │
│ Vision │ │  Go    │ │Nominat.│ │Calendar│ │ SMTP   │
│  API   │ │  API   │ │        │ │ (JSON) │ │ Email  │
└────────┘ └────────┘ └────────┘ └────────┘ └────────┘
'''
    
    arch_para = doc.add_paragraph()
    run = arch_para.add_run(arch_text)
    run.font.name = 'Consolas'
    run.font.size = Pt(8)
    
    doc.add_page_break()
    
    # ========== 3. HIGH-LEVEL DESIGN ==========
    doc.add_heading('3. High-Level Design (HLD)', 1)
    
    doc.add_heading('3.1 Design Principles', 2)
    
    table = doc.add_table(rows=6, cols=2)
    table.style = 'Table Grid'
    
    headers = ['Principle', 'Description']
    principles = [
        ('Accessibility First', 'All interactions optimized for blind/VI users'),
        ('Real-time Processing', 'Streaming responses for minimal latency'),
        ('Modular Architecture', 'Loosely coupled components for maintainability'),
        ('Privacy Aware', 'Thoughtful handling of visual data with people'),
        ('Fault Tolerant', 'Graceful degradation when services unavailable'),
    ]
    
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = headers[0]
    hdr_cells[1].text = headers[1]
    for cell in hdr_cells:
        cell.paragraphs[0].runs[0].font.bold = True
    
    for i, (principle, desc) in enumerate(principles, 1):
        row = table.rows[i].cells
        row[0].text = principle
        row[1].text = desc
    
    doc.add_paragraph()
    
    doc.add_heading('3.2 System Layers', 2)
    
    layers_text = '''
┌─────────────────────────────────────────────────────────────────────────────┐
│  LAYER 1: PRESENTATION LAYER                                                 │
│  ┌─────────────────────┐ ┌─────────────────────┐ ┌────────────────────────┐  │
│  │   Voice Interface   │ │   Video Interface   │ │   WebRTC Connection    │  │
│  │   (Microphone/      │ │   (Camera Feed)     │ │   (LiveKit Cloud)      │  │
│  │    Speaker)         │ │                     │ │                        │  │
│  └─────────────────────┘ └─────────────────────┘ └────────────────────────┘  │
└─────────────────────────────────────────────────────────────────────────────┘
                                      │
                                      ▼
┌─────────────────────────────────────────────────────────────────────────────┐
│  LAYER 2: PROCESSING LAYER                                                   │
│  ┌─────────────────────┐ ┌─────────────────────┐ ┌────────────────────────┐  │
│  │   Speech-to-Text    │ │   Language Model    │ │   Text-to-Speech       │  │
│  │   (Deepgram Nova-3) │ │   (Ollama qwen3-vl) │ │   (ElevenLabs)         │  │
│  └─────────────────────┘ └─────────────────────┘ └────────────────────────┘  │
│  ┌─────────────────────┐ ┌─────────────────────┐                             │
│  │   Voice Activity    │ │   Vision Processing │                             │
│  │   Detection (Silero)│ │   (VisualProcessor) │                             │
│  └─────────────────────┘ └─────────────────────┘                             │
└─────────────────────────────────────────────────────────────────────────────┘
                                      │
                                      ▼
┌─────────────────────────────────────────────────────────────────────────────┐
│  LAYER 3: BUSINESS LOGIC LAYER                                               │
│  ┌─────────────────────┐ ┌─────────────────────┐ ┌────────────────────────┐  │
│  │   AllyVisionAgent   │ │   Function Router   │ │   Tool Orchestrator    │  │
│  │   (Main Agent)      │ │   (Query Classifier)│ │   (Tool Execution)     │  │
│  └─────────────────────┘ └─────────────────────┘ └────────────────────────┘  │
└─────────────────────────────────────────────────────────────────────────────┘
                                      │
                                      ▼
┌─────────────────────────────────────────────────────────────────────────────┐
│  LAYER 4: INTEGRATION LAYER                                                  │
│  ┌───────────┐ ┌───────────┐ ┌───────────┐ ┌───────────┐ ┌───────────┐     │
│  │Visual Tool│ │Search Tool│ │Places Tool│ │Calendar   │ │Comm Tool  │     │
│  │           │ │           │ │           │ │Tool       │ │           │     │
│  └───────────┘ └───────────┘ └───────────┘ └───────────┘ └───────────┘     │
└─────────────────────────────────────────────────────────────────────────────┘
                                      │
                                      ▼
┌─────────────────────────────────────────────────────────────────────────────┐
│  LAYER 5: EXTERNAL SERVICES LAYER                                            │
│  ┌───────────┐ ┌───────────┐ ┌───────────┐ ┌───────────┐ ┌───────────┐     │
│  │  Ollama   │ │DuckDuckGo │ │   OSM     │ │  Local    │ │  IMAP/    │     │
│  │  Cloud    │ │  Search   │ │ Nominatim │ │ Calendar  │ │   SMTP    │     │
│  └───────────┘ └───────────┘ └───────────┘ └───────────┘ └───────────┘     │
└─────────────────────────────────────────────────────────────────────────────┘
'''
    
    layers_para = doc.add_paragraph()
    run = layers_para.add_run(layers_text)
    run.font.name = 'Consolas'
    run.font.size = Pt(8)
    
    doc.add_page_break()
    
    # ========== 4. COMPONENT ARCHITECTURE ==========
    doc.add_heading('4. Component Architecture', 1)
    
    doc.add_heading('4.1 Core Components', 2)
    
    table = doc.add_table(rows=5, cols=4)
    table.style = 'Table Grid'
    
    headers = ['Component', 'File', 'Description', 'Key Responsibilities']
    data = [
        ('App Entry', 'app.py', 'Application entry point', 'Initialize logging, start LiveKit CLI'),
        ('Agent Core', 'src/main.py', 'Main agent implementation', 'Handle user messages, route to tools'),
        ('Config Manager', 'src/config.py', 'Configuration management', 'Load environment variables, settings'),
        ('Utils', 'src/utils.py', 'Utility functions', 'Credential management, helpers'),
    ]
    
    hdr_cells = table.rows[0].cells
    for i, header in enumerate(headers):
        hdr_cells[i].text = header
        hdr_cells[i].paragraphs[0].runs[0].font.bold = True
    
    for i, row_data in enumerate(data, 1):
        row = table.rows[i].cells
        for j, cell_data in enumerate(row_data):
            row[j].text = cell_data
    
    doc.add_paragraph()
    
    doc.add_heading('4.2 Tool Components', 2)
    
    table = doc.add_table(rows=8, cols=4)
    table.style = 'Table Grid'
    
    headers = ['Tool', 'File', 'Purpose', 'External API']
    data = [
        ('VisualProcessor', 'tools/visual.py', 'Camera frame capture', 'LiveKit WebRTC'),
        ('OllamaHandler', 'tools/ollama_handler.py', 'Vision LLM processing', 'Ollama API'),
        ('InternetSearch', 'tools/internet_search.py', 'Web search', 'DuckDuckGo'),
        ('PlacesSearch', 'tools/google_places.py', 'Location search', 'OSM Nominatim'),
        ('CalendarTool', 'tools/calendar.py', 'Calendar management', 'Local JSON store'),
        ('CommunicationTool', 'tools/communication.py', 'Email/Contacts', 'IMAP/SMTP + Local JSON'),
        ('PipelineProfiler', 'tools/timing.py', 'Latency measurement', 'Internal'),
    ]
    
    hdr_cells = table.rows[0].cells
    for i, header in enumerate(headers):
        hdr_cells[i].text = header
        hdr_cells[i].paragraphs[0].runs[0].font.bold = True
    
    for i, row_data in enumerate(data, 1):
        row = table.rows[i].cells
        for j, cell_data in enumerate(row_data):
            row[j].text = cell_data
    
    doc.add_page_break()
    
    # ========== 5. WORKFLOW DIAGRAMS ==========
    doc.add_heading('5. Workflow Diagrams', 1)
    
    doc.add_heading('5.1 Main Application Workflow', 2)
    
    workflow_text = '''
    START
      │
      ▼
┌─────────────────┐
│  1. app.py      │
│  Initialize     │
│  logging        │
└────────┬────────┘
         │
         ▼
┌─────────────────┐
│  2. Load src/   │
│  __init__.py    │
│  (env vars)     │
└────────┬────────┘
         │
         ▼
┌─────────────────┐
│  3. cli.run_app │
│  with Worker    │
│  Options        │
└────────┬────────┘
         │
         ▼
┌─────────────────┐
│  4. Connect to  │
│  LiveKit Cloud  │
│  (WebSocket)    │
└────────┬────────┘
         │
         ▼
┌─────────────────┐
│  5. Initialize  │
│  UserData with  │
│  all tools      │
└────────┬────────┘
         │
         ▼
┌─────────────────┐
│  6. Create      │
│  AgentSession   │
│  (STT/LLM/TTS)  │
└────────┬────────┘
         │
         ▼
┌─────────────────┐
│  7. Start Agent │
│  Session with   │
│  Room I/O       │
└────────┬────────┘
         │
         ▼
    LISTENING
    FOR USER
    INPUT...
'''
    
    wf_para = doc.add_paragraph()
    run = wf_para.add_run(workflow_text)
    run.font.name = 'Consolas'
    run.font.size = Pt(9)
    
    doc.add_heading('5.2 Voice Interaction Workflow', 2)
    
    voice_workflow = '''
User Speaks
    │
    ▼
┌──────────────────┐
│ 1. SILERO VAD    │───▶ Detects voice activity, filters silence/noise
└────────┬─────────┘
         │ Audio Frames
         ▼
┌──────────────────┐
│ 2. DEEPGRAM STT  │───▶ Converts speech to text, real-time transcription
└────────┬─────────┘
         │ Transcribed Text
         ▼
┌──────────────────┐
│ 3. on_message()  │───▶ Logs query, sets up profiling
└────────┬─────────┘
         │ User Query
         ▼
┌──────────────────┐
│ 4. OLLAMA LLM    │───▶ Processes query, selects appropriate tool
└────────┬─────────┘
         │ Tool Selection
         ▼
┌──────────────────┐
│ 5. TOOL          │───▶ Executes selected tool, returns results
│    EXECUTION     │
└────────┬─────────┘
         │ Response Text
         ▼
┌──────────────────┐
│ 6. ELEVENLABS    │───▶ Converts text to speech, natural voice output
│    TTS           │
└────────┬─────────┘
         │ Audio Stream
         ▼
User Hears Response
'''
    
    voice_para = doc.add_paragraph()
    run = voice_para.add_run(voice_workflow)
    run.font.name = 'Consolas'
    run.font.size = Pt(9)
    
    doc.add_page_break()
    
    doc.add_heading('5.3 Vision Analysis Workflow', 2)
    
    vision_workflow = '''
User: "What do you see?"
         │
         ▼
┌──────────────────┐
│ 1. analyze_vision│───▶ Tool triggered by LLM
│ @function_tool   │
└────────┬─────────┘
         │
         ▼
┌──────────────────┐
│ 2. FRAME CAPTURE │───▶ Get video track from room
│ visual_processor │     Capture 5 frames buffer
│ .capture_frame() │     Return latest frame
└────────┬─────────┘
         │ Image (PIL)
         ▼
┌──────────────────┐
│ 3. CREATE VISUAL │───▶ Build ChatContext
│ CONTEXT          │     Add system prompt
│                  │     Add image + query
└────────┬─────────┘
         │ ChatContext
         ▼
┌──────────────────┐
│ 4. START ASYNC   │───▶ Non-blocking LLM call
│ LLM ANALYSIS     │     Stream chunks to queue
│ create_task()    │
└────────┬─────────┘
         │
         ▼
┌──────────────────┐
│ 5. STREAM        │───▶ Yield chunks as received
│ PROCESSING       │     Build full response
│ _process_stream()│     Handle timeouts
└────────┬─────────┘
         │ Response Chunks
         ▼
┌──────────────────┐
│ 6. TTS OUTPUT    │───▶ Convert to speech
│ Real-time        │     Stream audio to user
└────────┬─────────┘
         │
         ▼
User Hears Description
'''
    
    vision_para = doc.add_paragraph()
    run = vision_para.add_run(vision_workflow)
    run.font.name = 'Consolas'
    run.font.size = Pt(9)
    
    doc.add_page_break()
    
    # ========== 6. DATAFLOW DIAGRAMS ==========
    doc.add_heading('6. Dataflow Diagrams', 1)
    
    doc.add_heading('6.1 Complete System Dataflow', 2)
    
    dataflow_text = '''
┌─────────┐                                                          ┌─────────┐
│  USER   │                                                          │  USER   │
│ (Input) │                                                          │(Output) │
└────┬────┘                                                          └────▲────┘
     │ Voice/Camera                                               Audio │
     ▼                                                                  │
┌─────────────────────────────────────────────────────────────────────────────┐
│                              LIVEKIT CLOUD                                   │
│  ┌────────────┐                                      ┌────────────┐         │
│  │ Audio Track│──────┐                        ┌─────▶│Audio Track │         │
│  │ (WebRTC)   │      │                        │      │ (WebRTC)   │         │
│  └────────────┘      │                        │      └────────────┘         │
│  ┌────────────┐      │                        │                             │
│  │Video Track │──────┼────────────────────────┼─────────────────────────────│
│  │ (WebRTC)   │      │                        │                             │
│  └────────────┘      │                        │                             │
└──────────────────────┼────────────────────────┼─────────────────────────────┘
                       │                        │
                       ▼                        │
┌──────────────────────────────────────────────────────────────────────────────┐
│                      LIVEKIT AGENTS FRAMEWORK                                │
│                                               │                              │
│  ┌─────────────┐  ┌─────────────┐  ┌─────────┴───────┐  ┌─────────────┐     │
│  │  SILERO VAD │─▶│DEEPGRAM STT │─▶│   OLLAMA LLM    │─▶│ELEVENLABS TTS│    │
│  └─────────────┘  └─────────────┘  └────────┬────────┘  └─────────────┘     │
│                                             │                                │
│                                             ▼                                │
│                                ┌─────────────────────┐                       │
│                                │   AllyVisionAgent   │                       │
│                                │   Tool Selection    │                       │
│                                └──────────┬──────────┘                       │
└───────────────────────────────────────────┼──────────────────────────────────┘
                                            │
        ┌─────────────┬─────────────┬───────┼───────┬─────────────┐
        ▼             ▼             ▼       ▼       ▼             ▼
   ┌─────────┐   ┌─────────┐   ┌─────────┐ ┌─────────┐ ┌─────────┐ ┌─────────┐
   │ Visual  │   │Internet │   │ Places  │ │Calendar │ │  Comm   │ │ General │
   │ Query   │   │ Search  │   │ Search  │ │  Mgmt   │ │  Mgmt   │ │ Query   │
   └────┬────┘   └────┬────┘   └────┬────┘ └────┬────┘ └────┬────┘ └────┬────┘
        │             │             │           │           │           │
        ▼             ▼             ▼           ▼           ▼           │
   ┌─────────┐   ┌─────────┐   ┌─────────┐ ┌─────────┐ ┌─────────┐     │
   │ OLLAMA  │   │DuckDuck │   │   OSM   │ │ Local   │ │ IMAP/   │     │
   │ Vision  │   │  Go     │   │Nominat. │ │Calendar │ │  SMTP   │     │
   │ API     │   │  API    │   │         │ │ (JSON)  │ │  Email  │     │
   └────┬────┘   └────┬────┘   └────┬────┘ └────┬────┘ └────┬────┘     │
        │             │             │           │           │           │
        └─────────────┴─────────────┴───────────┴───────────┴───────────┘
                                    │
                                    ▼
                           ┌─────────────────┐
                           │   Tool Result   │
                           │  (Text Response)│
                           └────────┬────────┘
                                    │
                                    ▼
                           ┌─────────────────┐
                           │  Back to LLM    │
                           │  for Response   │
                           │  Generation     │
                           └─────────────────┘
'''
    
    df_para = doc.add_paragraph()
    run = df_para.add_run(dataflow_text)
    run.font.name = 'Consolas'
    run.font.size = Pt(7)
    
    doc.add_page_break()
    
    doc.add_heading('6.2 Data Format Specifications', 2)
    
    doc.add_heading('Input Data Formats', 3)
    table = doc.add_table(rows=4, cols=3)
    table.style = 'Table Grid'
    headers = ['Source', 'Format', 'Description']
    data = [
        ('Audio Input', 'PCM 16-bit, 16kHz', 'Voice from microphone'),
        ('Video Input', 'YUV420 frames', 'Camera via WebRTC'),
        ('STT Output', 'UTF-8 text', 'Transcribed speech'),
    ]
    hdr_cells = table.rows[0].cells
    for i, header in enumerate(headers):
        hdr_cells[i].text = header
        hdr_cells[i].paragraphs[0].runs[0].font.bold = True
    for i, row_data in enumerate(data, 1):
        row = table.rows[i].cells
        for j, cell_data in enumerate(row_data):
            row[j].text = cell_data
    
    doc.add_paragraph()
    
    doc.add_heading('Internal Data Formats', 3)
    table = doc.add_table(rows=5, cols=3)
    table.style = 'Table Grid'
    headers = ['Component', 'Format', 'Example']
    data = [
        ('Frame Buffer', 'PIL.Image', 'RGB image object'),
        ('Chat Context', 'ChatContext', 'Messages + ImageContent'),
        ('LLM Chunks', 'ChatChunk', 'Delta content streaming'),
        ('Tool Results', 'String', 'Formatted response text'),
    ]
    hdr_cells = table.rows[0].cells
    for i, header in enumerate(headers):
        hdr_cells[i].text = header
        hdr_cells[i].paragraphs[0].runs[0].font.bold = True
    for i, row_data in enumerate(data, 1):
        row = table.rows[i].cells
        for j, cell_data in enumerate(row_data):
            row[j].text = cell_data
    
    doc.add_page_break()
    
    # ========== 7. TECHNOLOGY STACK ==========
    doc.add_heading('7. Technology Stack', 1)
    
    doc.add_heading('7.1 Runtime & Language', 2)
    table = doc.add_table(rows=4, cols=2)
    table.style = 'Table Grid'
    data = [
        ('Python 3.11+', 'Primary language with async/await support'),
        ('asyncio', 'Asynchronous I/O framework'),
        ('dataclasses', 'Structured data management'),
    ]
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Technology'
    hdr_cells[1].text = 'Purpose'
    for cell in hdr_cells:
        cell.paragraphs[0].runs[0].font.bold = True
    for i, (tech, purpose) in enumerate(data, 1):
        row = table.rows[i].cells
        row[0].text = tech
        row[1].text = purpose
    
    doc.add_paragraph()
    
    doc.add_heading('7.2 LiveKit Ecosystem', 2)
    table = doc.add_table(rows=7, cols=2)
    table.style = 'Table Grid'
    data = [
        ('livekit-agents 1.3.12', 'Agent framework for voice AI'),
        ('livekit-plugins-deepgram', 'Deepgram STT integration'),
        ('livekit-plugins-openai', 'OpenAI-compatible LLM integration'),
        ('livekit-plugins-elevenlabs', 'ElevenLabs TTS integration'),
        ('livekit-plugins-silero', 'Silero VAD integration'),
        ('livekit-plugins-tavus', 'Optional avatar integration'),
    ]
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Package'
    hdr_cells[1].text = 'Purpose'
    for cell in hdr_cells:
        cell.paragraphs[0].runs[0].font.bold = True
    for i, (pkg, purpose) in enumerate(data, 1):
        row = table.rows[i].cells
        row[0].text = pkg
        row[1].text = purpose
    
    doc.add_paragraph()
    
    doc.add_heading('7.3 AI/ML Services', 2)
    table = doc.add_table(rows=5, cols=2)
    table.style = 'Table Grid'
    data = [
        ('Ollama (local)', 'Vision LLM hosting (qwen3-vl:235b-instruct-cloud)'),
        ('Deepgram Nova-3', 'Speech-to-text (cloud)'),
        ('ElevenLabs', 'Text-to-speech (eleven_multilingual_v2)'),
        ('Silero VAD', 'Voice activity detection (local)'),
    ]
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Service'
    hdr_cells[1].text = 'Purpose'
    for cell in hdr_cells:
        cell.paragraphs[0].runs[0].font.bold = True
    for i, (service, purpose) in enumerate(data, 1):
        row = table.rows[i].cells
        row[0].text = service
        row[1].text = purpose
    
    doc.add_paragraph()
    
    doc.add_heading('7.4 External APIs', 2)
    table = doc.add_table(rows=6, cols=2)
    table.style = 'Table Grid'
    data = [
        ('DuckDuckGo Search', 'Internet search (via langchain)'),
        ('OSM Nominatim', 'Location/business search (geopy)'),
        ('Local Calendar', 'Calendar event management (JSON)'),
        ('IMAP/SMTP', 'Email reading and sending'),
        ('Local Contacts', 'Contact management (JSON)'),
    ]
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'API'
    hdr_cells[1].text = 'Purpose'
    for cell in hdr_cells:
        cell.paragraphs[0].runs[0].font.bold = True
    for i, (api, purpose) in enumerate(data, 1):
        row = table.rows[i].cells
        row[0].text = api
        row[1].text = purpose
    
    doc.add_page_break()
    
    # ========== 8. API INTEGRATION DETAILS ==========
    doc.add_heading('8. API Integration Details', 1)
    
    doc.add_heading('8.1 Ollama Vision API', 2)
    
    doc.add_paragraph('Endpoint: http://localhost:11434/v1/chat/completions')
    
    api_format = '''
REQUEST FORMAT:
{
  "model": "qwen3-vl:235b-instruct-cloud",
  "messages": [
    {
      "role": "system",
      "content": "You are Ally, a vision assistant..."
    },
    {
      "role": "user",
      "content": [
        {"type": "text", "text": "What do you see?"},
        {"type": "image_url", "image_url": {"url": "data:image/..."}}
      ]
    }
  ],
  "stream": true,
  "max_tokens": 500,
  "temperature": 0.7
}

RESPONSE FORMAT (Streaming):
data: {"choices":[{"delta":{"content":"The"}}]}
data: {"choices":[{"delta":{"content":" scene"}}]}
data: {"choices":[{"delta":{"content":" shows"}}]}
...
data: [DONE]
'''
    
    api_para = doc.add_paragraph()
    run = api_para.add_run(api_format)
    run.font.name = 'Consolas'
    run.font.size = Pt(9)
    
    doc.add_heading('8.2 Deepgram STT Configuration', 2)
    
    stt_config = '''
deepgram.STT(
    model="nova-3",        # Latest Nova model for best accuracy
    language="en"          # English language
)

Features:
• Real-time streaming transcription
• Punctuation and formatting
• Low latency (~300ms)
• High accuracy for natural speech
'''
    
    stt_para = doc.add_paragraph()
    run = stt_para.add_run(stt_config)
    run.font.name = 'Consolas'
    run.font.size = Pt(9)
    
    doc.add_heading('8.3 ElevenLabs TTS Configuration', 2)
    
    tts_config = '''
elevenlabs.TTS(
    model="eleven_multilingual_v2"   # High-quality multilingual model
)

Features:
• Natural human-like voice synthesis
• Streaming audio output
• Emotional expression
• Multiple language support
'''
    
    tts_para = doc.add_paragraph()
    run = tts_para.add_run(tts_config)
    run.font.name = 'Consolas'
    run.font.size = Pt(9)
    
    doc.add_page_break()
    
    # ========== 9. SEQUENCE DIAGRAMS ==========
    doc.add_heading('9. Sequence Diagrams', 1)
    
    doc.add_heading('9.1 Voice Interaction Sequence', 2)
    
    seq_diagram = '''
  User        LiveKit       VAD      Deepgram     Agent       LLM         TTS
   │            │           │           │           │          │           │
   │──Voice────▶│           │           │           │          │           │
   │            │──Audio───▶│           │           │          │           │
   │            │           │──Detect──▶│           │          │           │
   │            │           │           │           │          │           │
   │            │           │    ┌──────┴──────┐    │          │           │
   │            │           │    │ Transcribe  │    │          │           │
   │            │           │    └──────┬──────┘    │          │           │
   │            │           │           │           │          │           │
   │            │           │           │───Text───▶│          │           │
   │            │           │           │           │          │           │
   │            │           │           │    ┌──────┴──────┐   │           │
   │            │           │           │    │ on_message()│   │           │
   │            │           │           │    │ Route Query │   │           │
   │            │           │           │    └──────┬──────┘   │           │
   │            │           │           │           │          │           │
   │            │           │           │           │──Query──▶│           │
   │            │           │           │           │          │           │
   │            │           │           │           │    ┌─────┴─────┐     │
   │            │           │           │           │    │ Process   │     │
   │            │           │           │           │    │ & Select  │     │
   │            │           │           │           │    │ Tool      │     │
   │            │           │           │           │    └─────┬─────┘     │
   │            │           │           │           │          │           │
   │            │           │           │           │◀─Stream──│           │
   │            │           │           │           │          │           │
   │            │           │           │           │───Text──────────────▶│
   │            │           │           │           │          │           │
   │            │           │           │           │          │   ┌───────┴───┐
   │            │           │           │           │          │   │ Synthesize│
   │            │           │           │           │          │   │ Speech    │
   │            │           │           │           │          │   └───────┬───┘
   │            │           │           │           │          │           │
   │◀───────────┼───────────┼───────────┼───────────┼──────────┼───Audio───│
   │            │           │           │           │          │           │
'''
    
    seq_para = doc.add_paragraph()
    run = seq_para.add_run(seq_diagram)
    run.font.name = 'Consolas'
    run.font.size = Pt(7)
    
    doc.add_page_break()
    
    # ========== 10. DEPLOYMENT ARCHITECTURE ==========
    doc.add_heading('10. Deployment Architecture', 1)
    
    doc.add_heading('10.1 Local Development Setup', 2)
    
    local_deploy = '''
┌─────────────────────────────────────────────────────────────────────────────┐
│                              DEVELOPER MACHINE                               │
│                                                                              │
│  ┌─────────────────────┐     ┌─────────────────────┐                        │
│  │    Python 3.11      │     │     Ollama Server   │                        │
│  │    Virtual Env      │     │  localhost:11434    │                        │
│  │    (.venv/)         │     │                     │                        │
│  │                     │     │  qwen3-vl:235b      │                        │
│  │  ┌───────────────┐  │     │  -instruct-cloud    │                        │
│  │  │   app.py      │  │────▶│                     │                        │
│  │  │   src/main.py │  │     └─────────────────────┘                        │
│  │  │   src/tools/* │  │                                                    │
│  │  └───────────────┘  │                                                    │
│  └──────────┬──────────┘                                                    │
│             │ WebSocket                                                      │
└─────────────┼────────────────────────────────────────────────────────────────┘
              │
              ▼
┌─────────────────────────────────────────────────────────────────────────────┐
│                              CLOUD SERVICES                                  │
│                                                                              │
│  ┌─────────────────┐  ┌─────────────────┐  ┌─────────────────┐              │
│  │   LiveKit Cloud │  │    Deepgram     │  │   ElevenLabs    │              │
│  │  Real-time      │  │   Cloud API     │  │   Cloud API     │              │
│  │  WebRTC         │  │  STT Service    │  │  TTS Service    │              │
│  └─────────────────┘  └─────────────────┘  └─────────────────┘              │
│                                                                              │
│  ┌─────────────────┐  ┌─────────────────┐  ┌─────────────────┐              │
│  │  OSM Nominatim  │  │ Local Calendar  │  │  IMAP / SMTP    │              │
│  │   (Places)      │  │   (JSON file)   │  │   (Email)       │              │
│  └─────────────────┘  └─────────────────┘  └─────────────────┘              │
│                                                                              │
└─────────────────────────────────────────────────────────────────────────────┘
'''
    
    deploy_para = doc.add_paragraph()
    run = deploy_para.add_run(local_deploy)
    run.font.name = 'Consolas'
    run.font.size = Pt(7)
    
    doc.add_page_break()
    
    # ========== 11. PERFORMANCE & TIMING ==========
    doc.add_heading('11. Performance & Timing', 1)
    
    doc.add_heading('11.1 Pipeline Latency Breakdown', 2)
    
    table = doc.add_table(rows=10, cols=3)
    table.style = 'Table Grid'
    
    headers = ['Component', 'Time (ms)', 'Status']
    data = [
        ('VAD Detection', '10-50', '🟢 Fast'),
        ('STT (Deepgram)', '200-400', '🟡 Moderate'),
        ('LLM First Token', '300-800', '🟡 Moderate'),
        ('LLM Complete Response', '500-2000', '🟠 Slow'),
        ('Vision Frame Capture', '50-100', '🟢 Fast'),
        ('Vision LLM First Token', '500-1500', '🟠 Slow'),
        ('Vision LLM Complete', '1000-3000', '🔴 Very Slow'),
        ('TTS Synthesis Start', '100-300', '🟡 Moderate'),
        ('TOTAL (Text Query)', '1000-2500', '🟠 Slow'),
    ]
    
    hdr_cells = table.rows[0].cells
    for i, header in enumerate(headers):
        hdr_cells[i].text = header
        hdr_cells[i].paragraphs[0].runs[0].font.bold = True
    
    for i, row_data in enumerate(data, 1):
        row = table.rows[i].cells
        for j, cell_data in enumerate(row_data):
            row[j].text = cell_data
    
    doc.add_paragraph()
    
    doc.add_heading('11.2 Timing Profiler', 2)
    doc.add_paragraph(
        'The system includes a built-in PipelineProfiler class in tools/timing.py that measures:'
    )
    
    timing_items = [
        'frame_capture - Camera frame acquisition time',
        'vision_llm_first_token - Time to first token from vision model',
        'vision_llm_complete - Total vision analysis time',
        'llm_first_token - Time to first token from text LLM',
        'llm_complete - Total LLM generation time',
        'total_message_processing - End-to-end latency'
    ]
    for item in timing_items:
        doc.add_paragraph(item, style='List Bullet')
    
    doc.add_page_break()
    
    # ========== 12. SUMMARY ==========
    doc.add_heading('12. Summary', 1)
    
    doc.add_heading('12.1 Key Takeaways', 2)
    
    table = doc.add_table(rows=7, cols=2)
    table.style = 'Table Grid'
    
    headers = ['Aspect', 'Description']
    data = [
        ('Architecture', 'Multi-layer, modular design with clear separation of concerns'),
        ('Real-time', 'Streaming architecture for low-latency voice interaction'),
        ('Vision', 'Integrated camera capture and AI-powered scene analysis'),
        ('Tools', 'Six function tools for comprehensive assistance'),
        ('Accessibility', 'Designed specifically for blind/VI users'),
        ('Scalability', 'Cloud-native with distributed agent workers'),
    ]
    
    hdr_cells = table.rows[0].cells
    for i, header in enumerate(headers):
        hdr_cells[i].text = header
        hdr_cells[i].paragraphs[0].runs[0].font.bold = True
    
    for i, row_data in enumerate(data, 1):
        row = table.rows[i].cells
        for j, cell_data in enumerate(row_data):
            row[j].text = cell_data
    
    doc.add_paragraph()
    
    doc.add_heading('12.2 File Structure Summary', 2)
    
    file_structure = '''
Voice-Vision-Assistant-for-Blind/
├── app.py                    # Entry point
├── requirements.txt          # Dependencies
├── .env                      # Environment config
├── src/
│   ├── __init__.py          # Package init, env loading
│   ├── config.py            # Configuration management
│   ├── main.py              # AllyVisionAgent implementation
│   ├── utils.py             # Utility functions
│   └── tools/
│       ├── visual.py        # VisualProcessor
│       ├── ollama_handler.py # OllamaHandler
│       ├── internet_search.py # InternetSearch
│       ├── google_places.py  # PlacesSearch (OSM Nominatim)
│       ├── calendar.py      # CalendarTool
│       ├── communication.py # CommunicationTool
│       └── timing.py        # PipelineProfiler
└── docs/
    └── Voice_Vision_Assistant_HLD.docx  # This document
'''
    
    fs_para = doc.add_paragraph()
    run = fs_para.add_run(file_structure)
    run.font.name = 'Consolas'
    run.font.size = Pt(9)
    
    # Final info
    doc.add_paragraph()
    doc.add_paragraph()
    final = doc.add_paragraph()
    final.alignment = WD_ALIGN_PARAGRAPH.CENTER
    final.add_run('─' * 50 + '\n')
    final.add_run('Document Version: 1.0\n').bold = True
    final.add_run('Last Updated: February 2, 2026\n')
    final.add_run('Author: Generated by GitHub Copilot\n')
    final.add_run('─' * 50)
    
    return doc

if __name__ == '__main__':
    doc = create_document()
    output_path = r'c:\Voice-Vision-Assistant-for-Blind\docs\Voice_Vision_Assistant_HLD.docx'
    doc.save(output_path)
    print(f'Document saved to: {output_path}')
